// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMMwkaBQCAehhIXmpCtAjZAofK3f5beKo',
    appId: '1:259048616873:web:c9811ab86deff593180ab8',
    messagingSenderId: '259048616873',
    projectId: 'faceapp-92c42',
    authDomain: 'faceapp-92c42.firebaseapp.com',
    storageBucket: 'faceapp-92c42.firebasestorage.app',
    measurementId: 'G-7T7G0MFBQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfv7c-QFFnKgOHaW6aIKQ1oVSIFMZDZb8',
    appId: '1:259048616873:android:a6c573e76e2450ee180ab8',
    messagingSenderId: '259048616873',
    projectId: 'faceapp-92c42',
    storageBucket: 'faceapp-92c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqcHCG-ZDK1bwcZPSQ-PUwVLSio0-1vs',
    appId: '1:259048616873:ios:9581122b1dab1412180ab8',
    messagingSenderId: '259048616873',
    projectId: 'faceapp-92c42',
    storageBucket: 'faceapp-92c42.firebasestorage.app',
    iosClientId: '259048616873-6pv1rcugta0jl2v602ag1cgcaia3cen0.apps.googleusercontent.com',
    iosBundleId: 'com.example.facelock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqcHCG-ZDK1bwcZPSQ-PUwVLSio0-1vs',
    appId: '1:259048616873:ios:9581122b1dab1412180ab8',
    messagingSenderId: '259048616873',
    projectId: 'faceapp-92c42',
    storageBucket: 'faceapp-92c42.firebasestorage.app',
    iosClientId: '259048616873-6pv1rcugta0jl2v602ag1cgcaia3cen0.apps.googleusercontent.com',
    iosBundleId: 'com.example.facelock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMMwkaBQCAehhIXmpCtAjZAofK3f5beKo',
    appId: '1:259048616873:web:8d3d9bc76d3d6865180ab8',
    messagingSenderId: '259048616873',
    projectId: 'faceapp-92c42',
    authDomain: 'faceapp-92c42.firebaseapp.com',
    storageBucket: 'faceapp-92c42.firebasestorage.app',
    measurementId: 'G-ZY2XYXGH73',
  );
}
